sudo: required

services:
- docker

env:
  global:
  - DOCKER_REPO: wbaa/airlock-dev-mariadb
  - secure: "PN2csOmSiOwyHN2a+Wy93jUiMOgezsnbAcsPnVy6yyvkEns29PuyImV9jyo4w40YJH2DoCCKFKwiFgPHPoIHyLAjTVh6eWXBqYALQInbHxsYX63tmMLnmCy0W/Vf0d2dfOn5Y6VndNzZcWWChoofV3Kszt1GABkPMZeyW7pFRx6ZKQYQRBNLnGCP3XdiVasTX+Ww6ZSa1cIYS4IwVIjJhjFRml9yJGLXVd087sJIKIuzKkLOqpN1rmASL0h3EQ9Ov5JEeSE8JqjLLyV0MMwsRARDziVj91gvHyAKJ8G1N86dUQMMb855vvWo01fqKPM/aKUWpxEigtHg3gmB+42uXj92iYBZNB0IwW1Nmu75K7Z61Oa5wA0sJZSIQZH2kw+L6dVZiwUn4DAY8N+ZO57Duoox2mAaUHDsSZGCJfbo59b4HIQsVjKnuzClsaY0rFUIOCavdUKNKqpnq0x7v7SwzOiRbSb5/YOZDE6476pyPrg4Jkc0PpELeMSkwZ+QP6TJJeW45uK6Ga0DAdcTgNka2vKidZv5ASSwn/PrF5BWxNg6aQpabUHJp58Ai4Yii82oeeYIJ5mXcM+5xg4N5/S8aZaV6xOi2kfb/JSZEYuE/w/w8TP9apCiRYyzUsnfoAhmURx2FeiCM9akVmhzQs5rAFBPXzuljlQaapvGtsLOu7U="
  - secure: "vGFL6QaVCx+nS4VqnwQgh2F/F9Gj+jrawy21tdkE5FpWStR35l29bPjNrQrPqzm2t/uQ367v+ITzZ8jdY7gRkdBNsLq2zeSSJPHM9pdd6H+eTPCZmF/JcNpA90kc6pC58Tgo2e422584YawsRx/vUdPEAiM7g8MG9VFWGZr2pDSAAfd3VJZR+kFAleDZQ6504x/xGFOqajgGwUqUk3ueZ0r3MAyh2/yE5pMvJmycZanFkflRzjzI52VoRIOpUse0s6X1XzfIir53P+awi9CthHQ5+ze7L5+C2NhE6xIrv5bGP0e+SCThFxPHq90iK8cj8doAzTuQajLBHsXh3YdnIvrGdC8OHAorp+PKJWrP15ntzqaRoqd5th/QaRnazuF5hilzj57uO3l/N9siD2/VvqmUSRcUcF5Nr/6DUzpv25TZt6gifdmKee9MzKl7gwvFH9CN+jPpElQh6CX43upNLAUPoa0Rme7jV/s8EtC8DnukqEs4Q1hjmp2Szqu8RV5hPeuNSj7O+mz6FAxaNyo1HPAwF9zqVnieH/EzrOLMyI63mYChOt0Uwic8s/KIQ85qNeesi7XHFtrK83JO+nLzQbJkCcohns06doAPikL73us0tDSJbMM+OndUs0AWJf7MaD+odPBKkgdFPE3vDRO59Um4fxDSAT/dvANhbOYgtOY="

# We will not build an image on the master tag, thereby forcing people to use tagged versions only
# Also there is an issue with using TRAVIS_BRANCH for PRs since this variable will be set to the target of the PR (e.g. master for PR to master) and then build an image for master unwanted before the merge happened
script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export DOCKER_TAG="${TRAVIS_BRANCH/\//_}"
- if [ "${TRAVIS_BRANCH}" != "master" ]; then 
    echo "Build image for with name $DOCKER_REPO:$DOCKER_TAG";
    docker pull $DOCKER_REPO:latest;
    travis_wait 80 docker build --quiet -t $DOCKER_REPO:$DOCKER_TAG .;
    docker push $DOCKER_REPO:$DOCKER_TAG;
  fi
- if [ -n "$TRAVIS_TAG" ]; then 
    docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:latest;
    docker push $DOCKER_REPO:latest;
  fi
